// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6gs0aCkAmqjqWmZxj2RyxdwGjcA5mQuA',
    appId: '1:102661071577:web:8ba8b070fe38599bed14c8',
    messagingSenderId: '102661071577',
    projectId: 'university-f0f7f',
    authDomain: 'university-f0f7f.firebaseapp.com',
    storageBucket: 'university-f0f7f.firebasestorage.app',
    measurementId: 'G-26XH53K289',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuaa-cZb-pGHYFLvWAXGy7pn2TZlT0sYY',
    appId: '1:102661071577:android:204e95d91efa6de0ed14c8',
    messagingSenderId: '102661071577',
    projectId: 'university-f0f7f',
    storageBucket: 'university-f0f7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbNTPbIj847RHCCx-_PSDTCZ5b1ckxJX0',
    appId: '1:102661071577:ios:fff12cbffee1a44eed14c8',
    messagingSenderId: '102661071577',
    projectId: 'university-f0f7f',
    storageBucket: 'university-f0f7f.firebasestorage.app',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbNTPbIj847RHCCx-_PSDTCZ5b1ckxJX0',
    appId: '1:102661071577:ios:fff12cbffee1a44eed14c8',
    messagingSenderId: '102661071577',
    projectId: 'university-f0f7f',
    storageBucket: 'university-f0f7f.firebasestorage.app',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6gs0aCkAmqjqWmZxj2RyxdwGjcA5mQuA',
    appId: '1:102661071577:web:a5840ffa19368f21ed14c8',
    messagingSenderId: '102661071577',
    projectId: 'university-f0f7f',
    authDomain: 'university-f0f7f.firebaseapp.com',
    storageBucket: 'university-f0f7f.firebasestorage.app',
    measurementId: 'G-2PM6V4PB3L',
  );
}
